name: expense_tracker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  circular_menu: ^2.0.1
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
  dots_indicator: ^3.0.0
  dotted_border: ^2.0.0+3
  dropdown_button2: ^2.3.7
  dropdown_button3: ^3.0.0
  fab_circular_menu_plus: ^0.0.1
  firebase_auth: ^4.9.0
  firebase_core: ^2.16.0
  fl_chart: ^0.63.0
  floating_bottom_bar: ^0.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.2
  google_fonts: ^6.0.0
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  line_icons: ^2.0.3
  magicon: ^0.0.3
  pinput: ^3.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  spline_chart: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - Assets/Images/

